version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=todo
    restart: always

  api:
    container_name: todo-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  data: {}
